### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Mogito89** [jia-kai/hearv#1]

**Comment by Mogito89** [comment]
hi,
how can test it?
thanks

**Comment by jia-kai** [comment]
This is just a project for a DSP course and I am sorry that I can not remember exactly :( If you do not have recorded video, I think you can try `synth_data.py` and `riesz/main.py`

**Comment by Mogito89** [comment]
ok thanks very much

**Comment by MaskRay** [comment]
膜一下~~开哥~~宋教授
